# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - pages/pub.md
  - pages/prj.md
  - pages/cv.md
  - pages/findme.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

style: dark # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

markdown: kramdown

plugins:
  - jekyll-seo-tag
